var files_dup =
[
    [ "dominios.cpp", "dominios_8cpp.html", null ],
    [ "dominios.h", "dominios_8h.html", [
      [ "Assento", "class_assento.html", "class_assento" ],
      [ "Bagagem", "class_bagagem.html", "class_bagagem" ],
      [ "CodigoBanco", "class_codigo_banco.html", "class_codigo_banco" ],
      [ "CodigoCarona", "class_codigo_carona.html", "class_codigo_carona" ],
      [ "CodigoReserva", "class_codigo_reserva.html", "class_codigo_reserva" ],
      [ "Cidade", "class_cidade.html", "class_cidade" ],
      [ "CPF", "class_c_p_f.html", "class_c_p_f" ],
      [ "Data", "class_data.html", "class_data" ],
      [ "Duracao", "class_duracao.html", "class_duracao" ],
      [ "Estado", "class_estado.html", "class_estado" ],
      [ "Email", "class_email.html", "class_email" ],
      [ "Nome", "class_nome.html", "class_nome" ],
      [ "Agencia", "class_agencia.html", "class_agencia" ],
      [ "NumeroConta", "class_numero_conta.html", "class_numero_conta" ],
      [ "Preco", "class_preco.html", "class_preco" ],
      [ "Telefone", "class_telefone.html", "class_telefone" ],
      [ "Senha", "class_senha.html", "class_senha" ],
      [ "Vagas", "class_vagas.html", "class_vagas" ]
    ] ],
    [ "entidades.cpp", "entidades_8cpp.html", null ],
    [ "entidades.h", "entidades_8h.html", [
      [ "Usuario", "class_usuario.html", "class_usuario" ],
      [ "Carona", "class_carona.html", "class_carona" ],
      [ "Reserva", "class_reserva.html", "class_reserva" ],
      [ "Conta", "class_conta.html", "class_conta" ]
    ] ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "testes.cpp", "testes_8cpp.html", null ],
    [ "testes.h", "testes_8h.html", [
      [ "TUAssento", "class_t_u_assento.html", "class_t_u_assento" ],
      [ "TUBagagem", "class_t_u_bagagem.html", "class_t_u_bagagem" ],
      [ "TUCodigoBanco", "class_t_u_codigo_banco.html", "class_t_u_codigo_banco" ],
      [ "TUCodigoCarona", "class_t_u_codigo_carona.html", "class_t_u_codigo_carona" ],
      [ "TUCodigoReserva", "class_t_u_codigo_reserva.html", "class_t_u_codigo_reserva" ],
      [ "TUCidade", "class_t_u_cidade.html", "class_t_u_cidade" ],
      [ "TUCPF", "class_t_u_c_p_f.html", "class_t_u_c_p_f" ],
      [ "TUData", "class_t_u_data.html", "class_t_u_data" ],
      [ "TUDuracao", "class_t_u_duracao.html", "class_t_u_duracao" ],
      [ "TUEstado", "class_t_u_estado.html", "class_t_u_estado" ],
      [ "TUEmail", "class_t_u_email.html", "class_t_u_email" ],
      [ "TUNome", "class_t_u_nome.html", "class_t_u_nome" ],
      [ "TUAgencia", "class_t_u_agencia.html", "class_t_u_agencia" ],
      [ "TUNumeroConta", "class_t_u_numero_conta.html", "class_t_u_numero_conta" ],
      [ "TUPreco", "class_t_u_preco.html", "class_t_u_preco" ],
      [ "TUTelefone", "class_t_u_telefone.html", "class_t_u_telefone" ],
      [ "TUSenha", "class_t_u_senha.html", "class_t_u_senha" ],
      [ "TUVagas", "class_t_u_vagas.html", "class_t_u_vagas" ],
      [ "TUUsuario", "class_t_u_usuario.html", "class_t_u_usuario" ],
      [ "TUCarona", "class_t_u_carona.html", "class_t_u_carona" ],
      [ "TUReserva", "class_t_u_reserva.html", "class_t_u_reserva" ],
      [ "TUConta", "class_t_u_conta.html", "class_t_u_conta" ]
    ] ]
];